contracts = {
    "HE": { "srf_name": "LN", "width": 4 },
    "LE": { "srf_name": "LC", "width": 4 },
    "ZC":  { "srf_name": "C", "width": 5 },
    "ZS": { "srf_name": "S", "width": 5 },
    "ZM": { "srf_name": "SM", "width": 5 },
    "ZL": { "srf_name": "BO", "width": 5 },
    "ZW": { "srf_name": "W", "width": 5 },
    "KE": { "srf_name": "KW", "width": 5 },
    "ZO": { "srf_name": "O", "width": 5 },
    "CL": { "srf_name": "CL", "width": 5 },
    "NG": { "srf_name": "NG", "width": 5 },
    "G": { "srf_name": "G", "width": 5 },
    "RB": { "srf_name": "RB", "width": 5 },
    "HO": { "srf_name": "HO", "width": 5 },
    "ATW": { "srf_name": "ATW", "width": 5 },
    "CC": { "srf_name": "CC", "width": 5 },
    "KC": { "srf_name": "KC", "width": 5 },
    "SB": { "srf_name": "SB", "width": 5 },
    "CT": { "srf_name": "CT", "width": 5 },
    "GE": { "srf_name": "ED", "width": 7 },
    "ZQ": { "srf_name": "FF", "width": 7 },
}
